### ISSUE TITLE
TypeError: sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by ryanhz** [ampledata/kiss#23]
>>> k.write(b'Hello, world!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/kiss/classes.py", line 197, in write
    kiss.FEND
TypeError: sequence item 0: expected str instance, bytes found

classes.py:193 should be frame_kiss = b''.join([

typo?

**Comment by masenf** [comment]
fixed by #25 and minimally by #28
