### ISSUE TITLE
can't pip install on MACOS

### ISSUE THREAD

**Issue by hemna** [ampledata/kiss#30]
```
└─> python setup.py develop
/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/pip-wheel-l2fk6y51/kiss_91ac76163f45464cad59c5d6f4deebcb/setup.py", line 32, in <module>
          setuptools.setup(
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 876, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 956, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 96, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/pip-wheel-l2fk6y51/kiss_91ac76163f45464cad59c5d6f4deebcb/.eggs/coverage-6.4.2-py3.8-macosx-11.2-x86_64.egg/coverage-6.4.2.dist-info' -> '/private/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/pip-wheel-l2fk6y51/kiss_91ac76163f45464cad59c5d6f4deebcb/.eggs/coverage-6.4.2-py3.8-macosx-11.2-x86_64.egg/EGG-INFO'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kiss
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/pip-wheel-l2fk6y51/kiss_91ac76163f45464cad59c5d6f4deebcb/setup.py", line 32, in <module>
          setuptools.setup(
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 876, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 956, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 96, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/pip-wheel-l2fk6y51/kiss_91ac76163f45464cad59c5d6f4deebcb/.eggs/coverage-6.4.2-py3.8-macosx-11.2-x86_64.egg/coverage-6.4.2.dist-info' -> '/private/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/pip-wheel-l2fk6y51/kiss_91ac76163f45464cad59c5d6f4deebcb/.eggs/coverage-6.4.2-py3.8-macosx-11.2-x86_64.egg/EGG-INFO'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for kiss
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/Users/i530566/.pyenv/versions/3.8.7/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/i530566/devel/mine/hamradio/kiss/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/tmpa6i5rn36', '--quiet', 'kiss>6.9']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    setuptools.setup(
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 876, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 789, in resolve
    dist = best[req.key] = env.best_match(
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1087, in obtain
    return installer(requirement)
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 956, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/Users/i530566/devel/mine/hamradio/kiss/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/Users/i530566/devel/mine/hamradio/kiss/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/2k/x4lk8j0n701_z8j8dr5f8yx00000gn/T/tmpa6i5rn36', '--quiet', 'kiss>6.9']' returned non-zero exit status 1.
```

**Comment by rupertdev** [comment]
run `pip3 install wheel` and then it will work
